[package]
name = "gaterust-tunnel"
description = "GateRust QUIC tunnel transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
atomic-write-file.workspace = true
futures-util.workspace = true
hmac.workspace = true
notify.workspace = true
pem.workspace = true
quinn.workspace = true
rand.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true
webpki-roots.workspace = true
x509-parser.workspace = true
zeroize.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile.workspace = true

[lints]
workspace = true
